/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PopularProduct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5438976090086080797L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PopularProduct\",\"namespace\":\"org.example.avro\",\"fields\":[{\"name\":\"window_start\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Start timestamp of the aggregation window in milliseconds since the epoch\"},{\"name\":\"window_end\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"End timestamp of the aggregation window in milliseconds since the epoch\"},{\"name\":\"location\",\"type\":\"string\",\"doc\":\"Location (mainly the country or the city) of the user\"},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Product\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"count\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PopularProduct> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PopularProduct> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PopularProduct> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PopularProduct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PopularProduct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PopularProduct to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PopularProduct from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PopularProduct instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PopularProduct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Start timestamp of the aggregation window in milliseconds since the epoch */
  private java.time.Instant window_start;
  /** End timestamp of the aggregation window in milliseconds since the epoch */
  private java.time.Instant window_end;
  /** Location (mainly the country or the city) of the user */
  private java.lang.CharSequence location;
  private java.util.List<org.example.avro.Product> products;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PopularProduct() {}

  /**
   * All-args constructor.
   * @param window_start Start timestamp of the aggregation window in milliseconds since the epoch
   * @param window_end End timestamp of the aggregation window in milliseconds since the epoch
   * @param location Location (mainly the country or the city) of the user
   * @param products The new value for products
   */
  public PopularProduct(java.time.Instant window_start, java.time.Instant window_end, java.lang.CharSequence location, java.util.List<org.example.avro.Product> products) {
    this.window_start = window_start.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.window_end = window_end.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.location = location;
    this.products = products;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return window_start;
    case 1: return window_end;
    case 2: return location;
    case 3: return products;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: window_start = (java.time.Instant)value$; break;
    case 1: window_end = (java.time.Instant)value$; break;
    case 2: location = (java.lang.CharSequence)value$; break;
    case 3: products = (java.util.List<org.example.avro.Product>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'window_start' field.
   * @return Start timestamp of the aggregation window in milliseconds since the epoch
   */
  public java.time.Instant getWindowStart() {
    return window_start;
  }


  /**
   * Sets the value of the 'window_start' field.
   * Start timestamp of the aggregation window in milliseconds since the epoch
   * @param value the value to set.
   */
  public void setWindowStart(java.time.Instant value) {
    this.window_start = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'window_end' field.
   * @return End timestamp of the aggregation window in milliseconds since the epoch
   */
  public java.time.Instant getWindowEnd() {
    return window_end;
  }


  /**
   * Sets the value of the 'window_end' field.
   * End timestamp of the aggregation window in milliseconds since the epoch
   * @param value the value to set.
   */
  public void setWindowEnd(java.time.Instant value) {
    this.window_end = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'location' field.
   * @return Location (mainly the country or the city) of the user
   */
  public java.lang.CharSequence getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * Location (mainly the country or the city) of the user
   * @param value the value to set.
   */
  public void setLocation(java.lang.CharSequence value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'products' field.
   * @return The value of the 'products' field.
   */
  public java.util.List<org.example.avro.Product> getProducts() {
    return products;
  }


  /**
   * Sets the value of the 'products' field.
   * @param value the value to set.
   */
  public void setProducts(java.util.List<org.example.avro.Product> value) {
    this.products = value;
  }

  /**
   * Creates a new PopularProduct RecordBuilder.
   * @return A new PopularProduct RecordBuilder
   */
  public static org.example.avro.PopularProduct.Builder newBuilder() {
    return new org.example.avro.PopularProduct.Builder();
  }

  /**
   * Creates a new PopularProduct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PopularProduct RecordBuilder
   */
  public static org.example.avro.PopularProduct.Builder newBuilder(org.example.avro.PopularProduct.Builder other) {
    if (other == null) {
      return new org.example.avro.PopularProduct.Builder();
    } else {
      return new org.example.avro.PopularProduct.Builder(other);
    }
  }

  /**
   * Creates a new PopularProduct RecordBuilder by copying an existing PopularProduct instance.
   * @param other The existing instance to copy.
   * @return A new PopularProduct RecordBuilder
   */
  public static org.example.avro.PopularProduct.Builder newBuilder(org.example.avro.PopularProduct other) {
    if (other == null) {
      return new org.example.avro.PopularProduct.Builder();
    } else {
      return new org.example.avro.PopularProduct.Builder(other);
    }
  }

  /**
   * RecordBuilder for PopularProduct instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PopularProduct>
    implements org.apache.avro.data.RecordBuilder<PopularProduct> {

    /** Start timestamp of the aggregation window in milliseconds since the epoch */
    private java.time.Instant window_start;
    /** End timestamp of the aggregation window in milliseconds since the epoch */
    private java.time.Instant window_end;
    /** Location (mainly the country or the city) of the user */
    private java.lang.CharSequence location;
    private java.util.List<org.example.avro.Product> products;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.avro.PopularProduct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.window_start)) {
        this.window_start = data().deepCopy(fields()[0].schema(), other.window_start);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.window_end)) {
        this.window_end = data().deepCopy(fields()[1].schema(), other.window_end);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.products)) {
        this.products = data().deepCopy(fields()[3].schema(), other.products);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PopularProduct instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.avro.PopularProduct other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.window_start)) {
        this.window_start = data().deepCopy(fields()[0].schema(), other.window_start);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.window_end)) {
        this.window_end = data().deepCopy(fields()[1].schema(), other.window_end);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.products)) {
        this.products = data().deepCopy(fields()[3].schema(), other.products);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'window_start' field.
      * Start timestamp of the aggregation window in milliseconds since the epoch
      * @return The value.
      */
    public java.time.Instant getWindowStart() {
      return window_start;
    }


    /**
      * Sets the value of the 'window_start' field.
      * Start timestamp of the aggregation window in milliseconds since the epoch
      * @param value The value of 'window_start'.
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder setWindowStart(java.time.Instant value) {
      validate(fields()[0], value);
      this.window_start = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'window_start' field has been set.
      * Start timestamp of the aggregation window in milliseconds since the epoch
      * @return True if the 'window_start' field has been set, false otherwise.
      */
    public boolean hasWindowStart() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'window_start' field.
      * Start timestamp of the aggregation window in milliseconds since the epoch
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder clearWindowStart() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'window_end' field.
      * End timestamp of the aggregation window in milliseconds since the epoch
      * @return The value.
      */
    public java.time.Instant getWindowEnd() {
      return window_end;
    }


    /**
      * Sets the value of the 'window_end' field.
      * End timestamp of the aggregation window in milliseconds since the epoch
      * @param value The value of 'window_end'.
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder setWindowEnd(java.time.Instant value) {
      validate(fields()[1], value);
      this.window_end = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'window_end' field has been set.
      * End timestamp of the aggregation window in milliseconds since the epoch
      * @return True if the 'window_end' field has been set, false otherwise.
      */
    public boolean hasWindowEnd() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'window_end' field.
      * End timestamp of the aggregation window in milliseconds since the epoch
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder clearWindowEnd() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * Location (mainly the country or the city) of the user
      * @return The value.
      */
    public java.lang.CharSequence getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * Location (mainly the country or the city) of the user
      * @param value The value of 'location'.
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder setLocation(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.location = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * Location (mainly the country or the city) of the user
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'location' field.
      * Location (mainly the country or the city) of the user
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder clearLocation() {
      location = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'products' field.
      * @return The value.
      */
    public java.util.List<org.example.avro.Product> getProducts() {
      return products;
    }


    /**
      * Sets the value of the 'products' field.
      * @param value The value of 'products'.
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder setProducts(java.util.List<org.example.avro.Product> value) {
      validate(fields()[3], value);
      this.products = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'products' field has been set.
      * @return True if the 'products' field has been set, false otherwise.
      */
    public boolean hasProducts() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'products' field.
      * @return This builder.
      */
    public org.example.avro.PopularProduct.Builder clearProducts() {
      products = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PopularProduct build() {
      try {
        PopularProduct record = new PopularProduct();
        record.window_start = fieldSetFlags()[0] ? this.window_start : (java.time.Instant) defaultValue(fields()[0]);
        record.window_end = fieldSetFlags()[1] ? this.window_end : (java.time.Instant) defaultValue(fields()[1]);
        record.location = fieldSetFlags()[2] ? this.location : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.products = fieldSetFlags()[3] ? this.products : (java.util.List<org.example.avro.Product>) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PopularProduct>
    WRITER$ = (org.apache.avro.io.DatumWriter<PopularProduct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PopularProduct>
    READER$ = (org.apache.avro.io.DatumReader<PopularProduct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










